import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { Bot, Cpu, MemoryStick, HardDrive, Terminal } from 'lucide-react';
import { DataTable, Badge, SlidePanel, Modal, LoadingSkeleton, EmptyState } from '../components/Layout';
import { useApi } from '../hooks/useApi';
import { api } from '../api/client';
export default function Agents() {
    const [selected, setSelected] = useState(null);
    const [execOpen, setExecOpen] = useState(false);
    const [cmd, setCmd] = useState('');
    const [filterStatus, setFilterStatus] = useState('all');
    const { data, loading, error, refresh } = useApi(() => api.getAgents(), { pollMs: 10000 });
    const agents = data || [];
    const filtered = filterStatus === 'all' ? agents : agents.filter((a) => a.status === filterStatus);
    if (loading && !data)
        return _jsx(LoadingSkeleton, { lines: 8 });
    return (_jsxs("div", { className: "space-y-6 fade-in", children: [error && !data && (_jsxs("div", { className: "flex flex-col items-center py-16 text-center", children: [_jsx("div", { className: "text-4xl mb-4 opacity-40", children: "\u26A0\uFE0F" }), _jsx("h3", { className: "text-lg font-semibold text-[var(--color-dim)]", children: "Unable to connect to relay" }), _jsx("p", { className: "mt-2 text-sm text-[var(--color-dim)] opacity-70", children: error }), _jsx("button", { onClick: refresh, className: "mt-4 rounded-xl bg-[var(--color-accent)] px-4 py-2 text-sm text-white hover:bg-[var(--color-accent-light)]", children: "Retry" })] })), _jsx("div", { className: "flex flex-wrap items-center gap-3", children: ['all', 'online', 'offline'].map(s => (_jsx("button", { onClick: () => setFilterStatus(s), className: `rounded-lg px-3 py-1.5 text-sm font-medium transition-colors ${filterStatus === s ? 'bg-[var(--color-accent)] text-white' : 'border border-[var(--color-border)] text-[var(--color-dim)] hover:text-[var(--color-text)]'}`, children: s === 'all' ? 'All' : s === 'online' ? '🟢 Online' : '🔴 Offline' }, s))) }), filtered.length === 0 && !error ? (_jsx(EmptyState, { icon: _jsx(Bot, { size: 48 }), title: "No agents found", description: filterStatus !== 'all' ? `No ${filterStatus} agents` : 'Deploy an agent to get started' })) : (_jsx(DataTable, { columns: [
                    { key: 'hostname', label: 'Hostname', render: (r) => (_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Bot, { size: 16, className: "text-[var(--color-accent)]" }), _jsxs("div", { children: [_jsx("div", { className: "font-medium", children: r.hostname }), _jsx("div", { className: "text-xs text-[var(--color-dim)]", children: r.id })] })] })) },
                    { key: 'os', label: 'OS', render: (r) => _jsx("span", { className: "text-xs font-mono", children: r.os }) },
                    { key: 'version', label: 'Version' },
                    { key: 'status', label: 'Status', render: (r) => (_jsxs(Badge, { variant: r.status === 'online' ? 'green' : 'red', children: [_jsx("span", { className: `inline-block h-1.5 w-1.5 rounded-full ${r.status === 'online' ? 'bg-emerald-400 pulse-dot' : 'bg-rose-400'}` }), r.status] })) },
                    { key: 'last_heartbeat', label: 'Last Heartbeat', render: (r) => _jsx("span", { className: "text-xs text-[var(--color-dim)]", children: new Date(r.last_heartbeat).toLocaleTimeString() }) },
                    { key: 'tags', label: 'Tags', render: (r) => _jsx("div", { className: "flex gap-1", children: (r.tags || []).map((t) => _jsx("span", { className: "rounded-md bg-[var(--color-surface3)] px-1.5 py-0.5 text-[10px] text-[var(--color-dim)]", children: t }, t)) }) },
                ], data: filtered, onRowClick: setSelected, searchPlaceholder: "Search agents..." })), _jsx(SlidePanel, { open: !!selected, onClose: () => setSelected(null), title: selected?.hostname || '', children: selected && (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 text-xl text-white", children: _jsx(Bot, {}) }), _jsxs("div", { children: [_jsx("div", { className: "font-semibold", children: selected.hostname }), _jsxs("div", { className: "text-sm text-[var(--color-dim)]", children: [selected.id, " \u00B7 ", selected.os] })] })] }), _jsx("div", { className: "grid grid-cols-3 gap-3", children: [
                                { label: 'CPU', value: `${selected.cpu ?? '—'}%`, icon: _jsx(Cpu, { size: 16 }), color: (selected.cpu ?? 0) > 80 ? 'text-rose-400' : 'text-emerald-400' },
                                { label: 'RAM', value: `${selected.ram ?? '—'}%`, icon: _jsx(MemoryStick, { size: 16 }), color: (selected.ram ?? 0) > 80 ? 'text-rose-400' : 'text-emerald-400' },
                                { label: 'Disk', value: `${selected.disk ?? '—'}%`, icon: _jsx(HardDrive, { size: 16 }), color: (selected.disk ?? 0) > 80 ? 'text-amber-400' : 'text-emerald-400' },
                            ].map(s => (_jsxs("div", { className: "rounded-xl border border-[var(--color-border)] bg-[var(--color-bg)] p-4 text-center", children: [_jsx("div", { className: `mb-1 flex justify-center ${s.color}`, children: s.icon }), _jsx("div", { className: "text-xl font-bold", children: s.value }), _jsx("div", { className: "text-xs text-[var(--color-dim)]", children: s.label })] }, s.label))) }), _jsxs("div", { className: "rounded-xl border border-[var(--color-border)] bg-[var(--color-bg)] p-4", children: [_jsx("div", { className: "text-xs text-[var(--color-dim)] uppercase tracking-wider mb-2", children: "System Info" }), _jsxs("div", { className: "grid grid-cols-2 gap-2 text-sm", children: [_jsxs("div", { children: [_jsx("span", { className: "text-[var(--color-dim)]", children: "IP:" }), " ", selected.ip || '—'] }), _jsxs("div", { children: [_jsx("span", { className: "text-[var(--color-dim)]", children: "Sessions:" }), " ", selected.sessions_count ?? '—'] }), _jsxs("div", { children: [_jsx("span", { className: "text-[var(--color-dim)]", children: "Version:" }), " ", selected.version] }), _jsxs("div", { children: [_jsx("span", { className: "text-[var(--color-dim)]", children: "Tags:" }), " ", (selected.tags || []).join(', ')] })] })] }), _jsxs("div", { className: "flex gap-3", children: [_jsxs("button", { onClick: () => setExecOpen(true), className: "flex-1 flex items-center justify-center gap-2 rounded-xl bg-[var(--color-accent)] py-2.5 text-sm font-medium text-white transition-all hover:bg-[var(--color-accent-light)]", children: [_jsx(Terminal, { size: 16 }), " Execute Command"] }), _jsx("button", { onClick: async () => { if (selected && confirm(`Disconnect ${selected.hostname}?`)) {
                                        try {
                                            await api.removeAgent(selected.id);
                                            refresh();
                                            setSelected(null);
                                        }
                                        catch { }
                                    } }, className: "flex-1 rounded-xl border border-rose-500/30 bg-rose-500/10 py-2.5 text-sm font-medium text-rose-400 transition-colors hover:bg-rose-500/20", children: "Disconnect" })] })] })) }), _jsxs(Modal, { open: execOpen, onClose: () => setExecOpen(false), title: "Execute Command", actions: _jsxs(_Fragment, { children: [_jsx("button", { onClick: () => setExecOpen(false), className: "rounded-lg border border-[var(--color-border)] px-4 py-2 text-sm", children: "Cancel" }), _jsx("button", { onClick: () => setExecOpen(false), className: "rounded-lg bg-[var(--color-accent)] px-4 py-2 text-sm text-white", children: "Execute" })] }), children: [_jsxs("div", { children: [_jsx("label", { className: "mb-1.5 block text-sm text-[var(--color-dim)]", children: "Command" }), _jsx("input", { type: "text", value: cmd, onChange: e => setCmd(e.target.value), placeholder: "e.g. systemctl restart nginx", className: "w-full rounded-lg border border-[var(--color-border)] bg-[var(--color-bg)] px-3 py-2.5 font-mono text-sm focus:border-[var(--color-accent)] focus:outline-none" })] }), _jsxs("div", { children: [_jsx("label", { className: "mb-1.5 block text-sm text-[var(--color-dim)]", children: "Shell" }), _jsxs("select", { className: "w-full rounded-lg border border-[var(--color-border)] bg-[var(--color-bg)] px-3 py-2.5 text-sm focus:border-[var(--color-accent)] focus:outline-none", children: [_jsx("option", { children: "/bin/bash" }), _jsx("option", { children: "/bin/sh" }), _jsx("option", { children: "/bin/zsh" })] })] })] })] }));
}
