[package]
name = "flowlink-k8s"
version = "0.3.4"
edition = "2021"

[dependencies]
flowlink-core = { path = "../core" }
flowlink-shield = { path = "../shield" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
anyhow = "1"
schemars = "0.8"
log = "0.4"
env_logger = "0.10"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4"] }
futures = "0.3"
thiserror = "1"
tracing = "0.1"
base64 = "0.21"
clap = { version = "4", features = ["derive", "env"] }

# K8s
kube = { version = "0.93", features = ["client", "runtime", "derive", "admission"] }
kube-derive = "0.93"
kube-core = "0.93"
k8s-openapi = { version = "0.24", features = ["v1_29"] }

# Webhook
axum = "0.8"
tower-http = { version = "0.6", features = ["cors"] }
rcgen = "0.11"
hyper = "1.0"
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }

[dev-dependencies]
tower = "0.5"
http = "1.0"
